version: '3.8'

services:
  mlflow_server:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow_server
    ports:
      - "5000:5000"
    volumes:
      - shared-mlflow-data:/mlflow_data
    command: >
      mlflow server 
      --host 0.0.0.0 
      --port 5000 
      --backend-store-uri sqlite:////mlflow_data/mlflow.db 
      --default-artifact-root /mlflow_data/artifacts

  api_service:
    build: .
    container_name: bank_churn_api
    ports:
      - "8000:8000"
    depends_on:
      - mlflow_server
    environment:
      - MLFLOW_TRACKING_URI=sqlite:////mlflow_data/mlflow.db
    volumes:
      - .:/app
      - shared-mlflow-data:/mlflow_data

volumes:
  shared-mlflow-data: